project:
  type: book
  output-dir: docs
  resources: 
    - V220254S.pdf
  
book:
  title: "MTH 304"
  subtitle: "Complex Functions"
#  cover-image: "images/whitaker.jpg"
  
  navbar:
    title: "mth 304 :: Complex Functions"
#    background: "#D0B8A8"
    search: true
    right:
      - href: glance.qmd
        text: At a Glance
  downloads: [pdf]
    
  sidebar:
    title: "wee title"
#    background: "#F8EDE3"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2
  
  chapters:
    - href: index.qmd
      text: "Welcome"
    - glance.qmd
    - inquiry.qmd
    - support.qmd
    - about.qmd
    - structure.qmd
    - grades.qmd
    - writing.qmd
    - UPElements.qmd
    
format:
  html:
    theme: [flatly, style/mth321.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    documentclass: memoir
    margin-left: 30mm
    margin-right: 30mm
    toc: true
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex
    include-in-header:  
        - text: |
            \usepackage{enumitem}

    
editor: visual

