---
title: "Course Content"
format: 
  html:
    number-sections: false
    toc-title: "On this page"
editor: visual
---

MTH 304 introduces the fundamental ideas and tool of complex variables and functions. A large part of this course is devoted to extending basic concepts from calculus to this new framework. Along the way, we'll get a glimpse how connecting the geometry of complex functions to ideas of calculus has far reaching consequences. Indeed, the study of complex variables opens up whole new avenues of research in a huge array of topics including algebraic geometry, analytic number theory, dynamical systems, signal analysis, and fluid mechanics just to name a few.

Specific topics that we'll cover in this course include

-   Representations of complex numbers
-   Fundamental complex-valued functions
-   Topology and limits in the complex plane
-   Derivatives and holomorphic functions
-   Series and analyticity
-   Contour integrals
-   Cauchy-Goursat theorem
-   Cauchy integral formula
-   Residue theorem

In addition to these specific *mathematical* topics, our learning goals also include:

-   communicating mathematics effectively
-   developing strategies for solving challenging, multi-step problems
-   developing a practice of self-reflection on one's own learning.

Certain affective traits (i.e., dispositions and habits that are useful for all learners, regardless of topic) are also valued, such as persistence and growth mindset, and the development of these qualities will be fostered by the course.
