---
title: "Grades"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

> Extrinsic motivation, which includes a desire to get better grades, is not only different from, but often undermines, intrinsic motivation, a desire to learn for its own sake.
>
> ::: {style="text-align: right"}
> -- Alfie Kohn, ["The Case Against Grades"](https://www.alfiekohn.org/article/case-grades/)
> :::

Grades, as they are traditionally thought of, are inherently imprecise and don't represent a full picture of your growth and learning over the course of a semester. Worse than that, research suggests that grades undermine the learning process in several ways:

-   Grades tend to diminish interest in what you're learning.
-   Grades create a preference for the easiest task. In other words, students tend to do what they need to get a certain grade, but no more.
-   Grades tend to reduce the quality of student thinking. The moment we ask \`\`**how** am I doing?'' we lose track of **what** we're doing.

## Qualitative Assessment

For these reasons, we will focus on **qualitative** not quantitative assessment. I will not be grading individual assignments but will instead give you feedback and comments that engage your work rather than simply evaluate it. After addressing that feedback, you're encouraged to resubmit for further feedback.

Throughout the semester, I will periodically ask you to reflect carefully on your work and to evaluate your progress. You will collect evidence of your understanding of the course content and based on that evidence, you will be asked to suggest a final course grade. In this way, we will determine your your grade collaboratively.

The intention here is to help you focus on learning in a way that is more organic, as opposed to simply working as you think you're expected to. If this process causes more anxiety than it alleviates, please see me at any point to confer about your progress in the course -- I'm always happy to talk with you about your learning!

Here some of the many ways that you might demonstrate your understanding of the course material:

-   Keep up with the daily Tasks and come to class ready to discuss and/or present your work.
-   Submit weekly homework, including revisions that incorporate feedback if needed, that reflects understanding of the class content.
-   Submit a portfolio that demonstrates your understanding of the course content as a whole body of knowledge, making connections between topics covered over the semester.

While I am required to submit a grade for each student at the end of the semester -- I will do what I can to de-emphasize the role of grades in this course so that as much as possible our focus is on learning.

## Grade Guidelines

If find it helpful to start with a qualitative description of what particular grades represent.

::: {.callout-note icon="false"}
## A

This grade generally indicates superior work that demonstrates a deep understanding of all of the course the material such that you could apply the material to new or unfamiliar situations. You can consistently demonstrate this understanding in a wide variety of ways.

A very good way to demonstrate an ability to extend your understanding to new topics is work beyond the material in the course notes. There are lots of applications of complex functions relevant as well as many interesting mathematical topics with connections to complex analysis. If you would like to explore additional topics, let me know and I can point you to additional resources.
:::

::: {.callout-note icon="false"}
## B 

This grade indicates good work that is eminently satisfactory. You will be able to use and extend this knowledge in many situations. To earn a B, you should consistently and/or frequently meet many criteria from the list above.
:::

::: {.callout-note icon="false"}
## C 

This grade indicates competent work that demonstrates an acceptable level of knowledge relevant to the course. To earn a C, you might consistently meet only a few of the criteria listed above or else meet several criteria but less often. In other words, maybe you do a few things very well and consistently, or else do many things fairly well but less often.
:::

::: {.callout-note icon="false"}
## D/F 

These grades represent a fundamental breakdown of expectations. A D represents a meaningful but unsuccessful attempt at earning a C or above. An F represents such a severe lack of engagement, effort, or understanding that there is no evidence of meaningful progress.
:::

## Engagement

Although your course grade will be based primarily on your **understanding** of course content and not on course engagement, in my experience these typically go hand in hand. So while engagement in the course is not itself evidence of understanding, it does usually help us achieve that goal.

Here are some ways that you can engage with the class:

- Come to class regularly, prepared to discuss that day's Tasks.  Work to make sense of new definitions or theorems (even if incorrrect!).  Try multiple approaches; include errors and comments on your thought process.
- Volunteer to present your work.  If you're not comfortable sharing your work with the whole class, you can share it in groups or during drop-in hours.
- Actively participate in class discussions and group work.  This can take many forms -- e.g. sharing your own work, asking questions, or helping to facilitate the discussion.
- Complete assignments on time.   Actively seek out resources to catch up if you miss class or if you have questions.
- Support classmates and help them succeed.
