---
title: "Course Structure"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
    number-sections: true
    
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

In broad strokes, this course is designed to engage you with rich problems in a collaborative setting. We will work in small groups on activities that engage the material -- solving problems and sharing your learning with your classmates. Outside of class, you will have Tasks to practice what we've learned and to stretch your problem solving skills. You will also be asked to reflect on your learning -- mathematics is as much about the problem solving process as it is about finding a correct answer and so reflecting and writing about your work is an important part of what we'll do.

## Attendence

Since we will be doing much of our learning through collaborative in-class activities, it's important that you to come to class prepared to engage and participate. That said, I also recognize that for many reasons, this will not always be possible. If you need to miss class \textbf{for any reason} just let me know -- there is no penalty apart from missing out on that day's activity. If you miss class often, you can expect me to reach out to see how I can support you coming to class.

[Poem 013: Did I Miss Anything? by Tom Wyman](https://www.loc.gov/programs/poetry-and-literature/poet-laureate/poet-laureate-projects/poetry-180/all-poems/item/poetry-180-013/did-i-miss-anything/)

I will do my best to post on Moodle a short summary of what we do in class, so if you do miss class, you should look there to see what we did that day. You may also find it helpful if you're able to check-in with a classmate to see what we covered. Finally, I'm always available in office hours to discuss anything you missed.

## Daily Tasks

Your standing assignment is to do the Tasks in the notes. You should work ahead so that you come to class having completed - or at least worked on - the Tasks for that day, ready to discuss or present your solutions.

While there is no requirement that everyone present their work, it is highly encouraged. The act of communicating your ideas to your classmates is a highly effective way to solidify and deepen your understanding of the material.

While my hope is that this class is a safe and supportive learning environment in which everyone feels welcome to share their ideas, I recognize that some students may have some anxiety around sharing their work. If this is the case, please let me know and we can find alternative ways for you to participate.

## Written Homework

Most every week, I will assign a short set of problems to write up and hand in. These might be new problems or they might be problems that we've seen in class already (i.e. daily Tasks).

This written homework serves a few different purposes. In many cases, it's an opportunity to refine or fill in any gaps of solutions that came up in class. In other cases, it gives you a chance to extend or apply ideas from class to new problem. Finally, homework is a place to practice communicating your understanding to others. Your goal in completing the homework is not just to find a solution, but to convince your reader that your solution is reasonable.

Homework is an opportunity to be challenged, make mistakes, struggle productively, and learn how to proceed in the face of uncertainty. Overall, the benefit lies as much in the process as it does in producing a correct answer.

### Feedback and Revisions

Weekly homework will not be graded in the usual sense - instead, I will provide feedback that addresses your progress towards learning the material, as well as your effectiveness in communicating your ideas. If you would like to revise any of your homework problems after getting feedback, you may hand it back in for further feedback **within one week**.

## Quizzes

We will likely have a few short in-class quizzes, generally at the end of each chapter to help you assess your progress.

## Due Dates

Just like in the "real world", due dates in this class exist and are important but there's usually a certain amount of flexibility. Life happens and sometimes circumstances may prevent you from completing an assignment on time. Or maybe you simply want a little more time to finish. For these reasons, you can (almost) always request an extension -- just send me an email. Note that if you ask for lots of extensions, you can expect that I will reach out to see if we can work together to find ways for you to keep up with the work in the course.

That said, there are reasons for having due dates. For one thing, they help you organize your life by helping you know how to budget your time. For another, they help me organize my life -- in particular, they help me keep up on getting your work back to you. If you hand in work after the due date, I cannot guarantee that I will get it back to you with useful feedback.

### Hard Deadlines {.unnumbered}

To prevent work from backing up, there are two **hard** deadlines in this course - one is February 28th (the Friday before spring break) and the other is April 21st (the last day of classes). Late work will not be accepeted after those dates, except by prior arrangment.

## Portfolio

As we proceed through the course material, I will periodically ask you to select examples of your work that demonstrate your understanding of the material. By the end of the semester, you should have a carefully curated collection of work that tells the story of you as a mathematician and student of complex variables and which provides evidence of your learning throughout the semester.  Assembling your portfolio is also a way to reflect on the course as a whole.

-   **Due date** Your portfolio should be complete by the last day of classes, April 25th. If you need more time, please let me know ahead of time.

-   **What do I include in the portfolio?**

    -   Table of contents. List all items in the portfolio in the order they are included. Include the number and name of each Task or Homework Problem, or a title for any other items (e.g. Presentation of Task 54 on 2/23).

    -   Artifacts that provide evidence of your learning. These will likely include many of your homework problems or daily Tasks, but can include other items too. For example:

        -   Did you have great work on a daily prep, but didn't present it? Share your notes!

        -   Did you give a presentation of a particularly significant problem? Include it!

        -   Did you work on optional problems, or Tasks that we skipped or didn't get to?

        -   Did you research an application or theorem that we didn't cover?

    - Include with each artifact a brief explanation of how it reflects your learning (e.g. what particular topics are represented) and why you selected that particular piece of work.
    
    
-   **Revisions** You can revise any homework or other artifacts again before including them in the portfolio. Your goal is to show how you've met the criteria for each grade by the end of the semester. If something confused you early on, but you've figured it out, that's great -- show me!

<!-- ## Final Project -->

<!-- This is an opportunity to apply your mathematical knowledge gained from the course and dig a bit deeper into a relevant topic of your choosing. You might expand on some topic or idea from the notes or else find a completely new idea to explore. The goal is for you to demonstrate your interest in and understanding of concepts, topic or applications of Complex Analysis. The secondary goal is to demonstrate your communication skills in mathematics. -->

<!-- This will generally involve finding and reading additional resources, and I am happy to help you with this by pointing you in the right direction. I'd also suggest carefully reading my thoughts about using GenAI tools in @sec-genai. -->

<!-- Here is a partial list of possible project ideas: -->

<!-- -   Applications to physics such as fluid mechanics, heat flow, electrostatics, quantum mechanics -->

<!-- -   Painleve' equations -->

<!-- -   Asymptotic analysis of integrals -->

<!-- -   Riemann-Hilbert problems -->

<!-- -   Highlights of analytic number theory -->

<!-- -   Conformal mappings -->

<!-- -   The Riemann zeta function -->

<!-- -   Lambert W-function -->

<!-- -   Laplace transforms -->

<!-- -   Fourier transforms -->

<!-- -   Functions on the Riemann sphere -->

## Final Reflection

Instead of a final exam, I will ask you to complete a final self-evaluation of your learning in this course. The goal is give you an opportunity to summarize what you've learned and how your understanding of the material has evolved over the course of the semester.
